module.exports = {
  collectCoverage: false,
  coverageDirectory: 'jest-coverage',
  collectCoverageFrom: [
    '**components/**/*.{js,jsx,ts,tsx}',
    '**pages/**/*.{js,jsx,ts,tsx}',
    '<rootDir>/*.{js,jsx,ts,tsx}',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/aliases.js',
    '<rootDir>/build-server/',
    '<rootDir>/dev-server/',
    '<rootDir>/jest.config.js',
    '<rootDir>/locales',
    '<rootDir>/next.config.js',
    '<rootDir>/node_modules',
    '<rootDir>/pages/_app.jsx',
    '<rootDir>/pages/_document.jsx',
    '<rootDir>/polyfills.js',
    '<rootDir>/public/',
    '<rootDir>/theme.js',
    '<rootDir>/translations.js',
    '<rootDir>/webpack.config.js',
  ],
  reporters: ['default', 'jest-junit'],
  testPathIgnorePatterns: ['<rootDir>/node_modules', '<rootDir>/public/'],
  testEnvironment: 'jsdom',
  verbose: false,
  moduleNameMapper: {
    '^api$': '<rootDir>/api.ts',
    '^codes$': '<rootDir>/codes.ts',
    '^components/(.*)': '<rootDir>/components/$1',
    '^config$': '<rootDir>/config.js',
    '^context/(.*)': '<rootDir>/context/$1',
    '^getPageMeta$': '<rootDir>/getPageMeta.ts',
    '^hooks/(.*)': '<rootDir>/hooks/$1',
    '^i18n$': '<rootDir>/i18n.js',
    '^layouts/(.*)': '<rootDir>/layouts/$1',
    '^locales$': '<rootDir>/locales.ts',
    '^theme$': '<rootDir>/theme.js',
    '^translations$': '<rootDir>/translations.js',
    '^types$': '<rootDir>/types.ts',
  },
};
